accounts/urls.py
# urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
    
]

server/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tasks.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("accounts.urls")),
]

tasks/urls.py
from django.urls import path
from .views import *


urlpatterns = [
     path('tasks/', ModelTaskDetail.as_view(), name = "alltasks"),
    path("", HomePageView.as_view() , name="homepage"),
    path("create/", TaskCreate.as_view() , name="create"),
    path("<int:pk>", TaskDetail.as_view(), name="task_detail"),
    path("<int:pk>/edit", EditTask.as_view(), name="task_edit"),
    path("<int:pk>/delete", DeleteTask.as_view(), name="task_delete"),
    
]

accounts/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.PositiveSmallIntegerField(default=1)
    is_done = models.BooleanField(default=False)
    created_at = models.DateField(auto_now=True)
    due_date = models.DateField(null=True)
    title = models.CharField(max_length=30)
    description = models.TextField()


    def __str__(self):
        return f"{self.user}: {self.title} ({self.due_date}) {self.description} {self.priority} {self.created_at} {self.is_done} "  

    def get_absolute_url(self):
        return "/tasks/%i/" % self.id

tasks/forms.py
from django.forms import ModelForm, TextInput, Textarea,CheckboxInput
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        exclude = ("user", "is_done")
        widgets = {
               'priority': TextInput(attrs={
                'style': 'max-width: 300px;margin-left:32px;background-color:black;color :white;border-radius:5px;height:40px;',
                'placeholder': 'Priority'
                }),
                'due_date': TextInput(attrs={
                'style': 'max-width: 300px;margin-left:20px;background-color:black;color :white;border-radius:5px;height:40px',
                'placeholder': 'Due-date'
                }),
                'title': TextInput(attrs={
                'style': 'max-width: 300px;margin-left:50px;background-color:black;color :white;border-radius:5px;height:40px',
                'placeholder': 'Title'
                }),
                'description': Textarea(attrs={
                'style': 'max-width: 300px;background-color:black;color :white;border-radius:5px;height:100px;margin-top:15px',
                'placeholder': 'Description'
                }),
        }

class EditForm(ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        exclude = ("user",)
        widgets = {
               'priority': TextInput(attrs={
                'style': 'max-width: 300px;margin-left:32px;background-color:black;color :white;border-radius:5px;height:40px;',
                'placeholder': 'Priority'
                }),
                'is_done': CheckboxInput(attrs={
                'style': 'width:30px;height:30px;backgruond-color:black;margin-left:30px',
                'placeholder': 'Priority'
                }),
                'due_date': TextInput(attrs={
                'style': 'max-width: 300px;margin-left:20px;background-color:black;color :white;border-radius:5px;height:40px',
                'placeholder': 'Due-date'
                }),
                'title': TextInput(attrs={
                'style': 'max-width: 300px;margin-left:50px;background-color:black;color :white;border-radius:5px;height:40px',
                'placeholder': 'Title'
                }),
                'description': Textarea(attrs={
                'style': 'max-width: 300px;background-color:black;color :white;border-radius:5px;height:100px;margin-top:15px',
                'placeholder': 'Description'
                }),
        }

    

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

tasks/views.py
from .models import Task
from django.views.generic import TemplateView, ListView, DetailView,CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy
from .forms import EditForm, TaskForm
# Create your views here.

class HomePageView(TemplateView):
    template_name = "tasks/homepage.html"

class ModelTaskDetail(ListView):
    model = Task
    template_name = "tasks/all_tasks.html"

class TaskCreate(CreateView):
    form_class = TaskForm 
    template_name = 'tasks/create.html'
    success_url = reverse_lazy("alltasks")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class TaskDetail(DetailView):
    model = Task
    template_name = "tasks/task_detail.html"
    context_object_name = 'task'     

class EditTask(UpdateView):
    form_class = EditForm
    model = Task
    template_name = "tasks/task_edit.html"
    success_url = reverse_lazy("alltasks")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form) 

class DeleteTask(DeleteView):
    model = Task
    template_name = "tasks/task_delete.html"
    success_url = reverse_lazy("alltasks")    
   
    

tasks/templates/tasks/all_tasks.html
{% extends "tasks/base.html" %}
{% block title %}All tasks{% endblock %}
      {% if user.is_authenticated %}
{% block content %}

<style>
  .a1:hover
  {
    color: dimgray;
  }
  .a1
  {
    text-decoration: none;
    color: black;
  }
  table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

    <div >
        <h1 style="text-align: center;">My tasks</h1>
        <p style="text-align: center;">Click task name to see details or edit it</p>
        <table>

          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Priority</th>
            <th>Due Date</th>
            <th>Created At</th>
            <th>Status</th>
          </tr>
          
            {% for i in task_list%}
            {% if i.user == user or user.is_superuser or not user.is_active and user.is_authenticated %}

            <tr> 
                <td class="td1"><a class="a1" href="{% url 'task_detail' i.pk %}">
                    {{i.title}}
</a></td>
                <td>{{ i.description }}<br></td>
                <td>{{ i.priority }}<br></td>
                <td>{{ i.due_date }}<br></td>
                <td>{{ i.created_at }}<br></td>
                {% if i.is_done == False %}<td>Not completed</td>
                {% else %}<td>Completed</td>{% endif %}
            </tr>
            {% endif %}
        {% endfor %} 
        </table>
      </div>
{% endblock content %}  
{% endif %}

tasks/templates/tasks/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/tasks.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
  </html>
  <style>
    a
    {
      text-decoration: none;
    }
    nav ul li a
    {
      text-decoration: none;
      margin-left: 20px;
      color: white;
      font-weight: 500;
    }
    nav ul li a:hover
    {
      color: dimgray;
      font-weight: 900;
    }
    body {
      font-family: 'Roboto', sans-serif;
      margin: 0;
      padding: 0;
    }
    nav {
      background-color: #333;
      color: #fff;
      padding: 10px;
    }
    .content {
      max-width: 800px;
      margin: 20px auto;
      padding: 20px;
      border: 1px solid #e2e2e2;
      border-radius: 5px;
      background-color: #f9f9f9;
    }
    .but1
    {
      height: 55px;
      border: 2px solid white;
      padding: 10px 25px;
      border-radius: 5px;
      color: white;
      font-size: 20px;
      margin-left: 30px;
    }
    .but1:hover
    {
      color: black;
      background-color: white;
      transition: all 1s;
    }
    .but2
    {
      height: 55px;
      border: 3px solid rgba(255, 255, 0, 0.463) ;
      padding: 10px 25px;
      border-radius: 5px;
      color: rgba(255, 255, 0, 0.463);
      font-size: 20px;
      margin-left: 30px;
    }
    .but2:hover
    {
      color: black;
      background-color: rgba(255, 255, 0, 0.463);
      transition: all 1s;
    }
  </style>
</head>
<body>
  <nav style="background-color: black;height: 100px;display: flex;position: fixed;width: 100%;z-index: 10;">
    <ul style="display: flex;list-style: none;margin-left: 70%;margin-top:30px;">
      <li><a href="{% url 'homepage' %}">Home</a></li>
      {% if  user.is_authenticated %}
      <li><a href="{% url 'alltasks' %}">Tasks</a></li>
      <li><a href="{% url 'create' %}">Add Task</a></li>
      {% endif %}
    </ul>
    <div style="margin: auto 10px;">
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}?next=/" class="but1">Logout</a>
      {% else %}
        <a href="{% url 'signup' %}" class="but2">Sign Up</a>
        <a href="{% url 'login' %}" class="but1">Sign In</a>
      {% endif %}
    </div>
  </nav>

  <div class="content" style="position: relative;top:200px;margin-top: 0px;">
  {% block content  %}{% endblock content %}
  </div>
  <div style="width: 100%;background-color: black;height: 200px;position: absolute;bottom: -100px;">
    <p style="text-align: center;color: white;font-size: 25px;padding-top: 50px;">CREATED BY MUHAMMADJON</p>
    <p style="text-align: center;color: white;font-size: 25px;">For more info <a href="https://t.me/individualy_01">Click here</a></p>
  </div>
</body>
</html> 

tasks/templates/tasks/create.html
{% extends "tasks/base.html" %}

{% block title %}Create task{% endblock %}
{% block content %}
<style>
.custom_form {
    margin: 20px auto;
    padding: 20px;
    background-color: white;
    border: 1px solid #ddd;
    border-radius: 5px;
    width: 50%;
    display: grid;
    justify-items: flex-start;
    align-content: center;
  }
  .but1
    {
      height: 55px;
      border: 2px solid white;
      padding: 10px 25px;
      border-radius: 5px;
      color: white;
      font-size: 20px;
      margin-left: 30px;
    }
    .but1:hover
    {
      color: black;
      background-color: white;
      transition: all 1s;
    }
    .but3
    {
      height: 55px;
      border: 2px solid black;
      padding: 10px 25px;
      border-radius: 5px;
      color: black;
      font-size: 20px;
      margin-left: 100px;
    }
    .but3:hover
    {
      color: white;
      background-color: black;
      transition: all 1s;
    }
  </style>
<form action="" method="post" class="custom_form" >
    {% csrf_token %}
    {{ form.as_p}}
    <button  type="submit" class="but3" >Submit</button>
</form>
{% endblock content %}     

tasks/templates/tasks/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 
</head>
  </html>
  <style>
    a
    {
      text-decoration: none;
    }
    nav ul li a
    {
      text-decoration: none;
      margin-left: 20px;
      color: white;
      font-weight: 500;
    }
    nav ul li a:hover
    {
      color: dimgray;
      font-weight: 900;
    }
    body {
      font-family: 'Roboto', sans-serif;
      margin: 0;
      padding: 0;
    }
    nav {
      background-color: #333;
      color: #fff;
      padding: 10px;
    }
    .content {
      max-width: 800px;
      margin: 20px auto;
      padding: 20px;
      border: 1px solid #e2e2e2;
      border-radius: 5px;
      background-color: #f9f9f9;
    }
    .but1
    {
      height: 55px;
      border: 2px solid white;
      padding: 10px 25px;
      border-radius: 5px;
      color: white;
      font-size: 20px;
      margin-left: 30px;
    }
    .but1:hover
    {
      color: black;
      background-color: white;
      transition: all 1s;
    }
    .but2
    {
      height: 55px;
      border: 3px solid rgba(255, 255, 0, 0.463) ;
      padding: 10px 25px;
      border-radius: 5px;
      color: rgba(255, 255, 0, 0.463);
      font-size: 20px;
      margin-left: 30px;
    }
    .but2:hover
    {
      color: black;
      background-color: rgba(255, 255, 0, 0.463);
      transition: all 1s;
    }
  </style>
</head>
<body>
  <nav style="background-color: black;height: 100px;display: flex;position: fixed;width: 100%;z-index: 10;">
    <ul style="display: flex;list-style: none;margin-left: 70%;margin-top:30px;">
      <li><a href="{% url 'homepage' %}">Home</a></li>
      {% if  user.is_authenticated %}
      <li><a href="{% url 'alltasks' %}">Tasks</a></li>
      <li><a href="{% url 'create' %}">Add Task</a></li>
      {% endif %}
    </ul>
    <div style="margin: auto 10px;">
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}?next=/" class="but1">Logout</a>
      {% else %}
        <a href="{% url 'signup' %}" class="but2">Sign Up</a>
        <a href="{% url 'login' %}" class="but1">Sign In</a>
      {% endif %}
    </div>
  </nav>

  <div >
    <div class="div1" style="width: 100%;height: 600px;background-repeat: no-repeat;background-position: center;background-size: cover;padding-top: 200px;background-image: url({% static 'images/photo1.jpg' %});">
        <p style="font-size: 50px;letter-spacing: 10px;font-family: sans-serif; font-weight: 900;color: white;text-align: center;">Task manager</p>
        <p style="font-size: 30px;font-weight: 500;font-family: sans-serif;color: white;text-align: center;">The task manager helps users organize and prioritize their to-do lists efficiently!</p> 
       </div>
       <p style="font-size: 30px;font-family: sans-serif; font-weight: 900;color: black;text-align: center;margin-top: 50px;">WHAT CAN DO MY TASK MANAGER</p>
       <div style="display: flex; width: 1200px;flex-wrap: wrap;column-gap:70px;margin-left: 18%;row-gap: 50px;margin-top: 50px;">
       <div class="card shadow-sm" style="width: 350px;">
        <div class="card-body">
          <p style="font-weight: 900;font-size: 30px;">ADD</p>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
      </div>
      <div class="card shadow-sm" style="width: 350px;">
      <p style="font-weight: 900;font-size: 30px;margin-left: 20px;margin-top: 20px">REMOVE</p>
        <div class="card-body">
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
      </div><div class="card shadow-sm" style="width: 350px;">
      <p style="font-weight: 900;font-size: 30px;margin-left: 20px;margin-top: 20px">STATUS</p>
        <div class="card-body">
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
      </div><div class="card shadow-sm "style="width: 350px;">
      <p style="font-weight: 900;font-size: 30px;margin-left: 20px;margin-top: 20px">SHOW ALL TASKS</p>
        <div class="card-body">
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
      </div><div class="card shadow-sm "style="width: 350px;">
      <p style="font-weight: 900;font-size: 30px;margin-left: 20px;margin-top: 20px">SHOW TODAY TASKS</p>
        <div class="card-body">
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
      </div><div class="card shadow-sm" style="width: 350px;">
      <p style="font-weight: 900;font-size: 30px;margin-left: 20px;margin-top: 20px;">SORT BY PRIORITY</p>
        <div class="card-body">
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
    </div>
    </div>
  </div>
  <div style="width: 100%;background-color: black;height: 200px;position: absolute;margin-top: 100px;">
    <p style="text-align: center;color: white;font-size: 25px;padding-top: 50px;">CREATED BY MUHAMMADJON</p>
    <p style="text-align: center;color: white;font-size: 25px;">For more info <a href="https://t.me/individualy_01">Click here</a></p>
  </div>
</body>
</html> 

tasks/templates/tasks/task_delete.html
{% extends "tasks/base.html" %}
{% block title %}Task delete{% endblock %}
{% block content %}

<h1 style="text-align: center;">Delete the task</h1>
<style>
        
    .but1
    {
      height: 55px;
      border: 2px solid black;
      padding: 10px 25px;
      border-radius: 5px;
      color: black;
      font-size: 20px;
      margin-left: 30px;
    }
    .but1:hover
    {
      color: white;
      background-color: black;
      transition: all 1s;
    }
</style>

<form action="" method="post">
    {% csrf_token %}

    <p style="text-align: center;">You really want to delete <b>"{{task.title}}"</b></p>
    <input type="submit" value="Delete it!" class="but1" style="margin-left:40%;">
</form>


{% endblock content %}

tasks/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}
{% block title %}Task deteils{% endblock %}
{% block content %}
<style>
    table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
.edit_link1 {
    padding: 20px 30px;
    background-color: black;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    transition:all 0.3s ease;
    font-weight: bold;
    margin: auto;
   
    width: 70%;
    margin-left: 200px;
    text-align: center;
  }
  
  .edit_link1:hover {
    background-color: white;
    transform: translateY(-2px);
    border: 3px solid black;
    box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
    color: black;
  }
  .edit_link2 {
    padding: 20px 30px;
    background-color: black;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    transition:all 0.3s ease;
    font-weight: bold;
    margin: auto;
   
    width: 70%;
    margin-left: 50px;
    text-align: center;
  }
  
  .edit_link2:hover {
    background-color: white;
    transform: translateY(-2px);
    border: 3px solid black;
    box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
    color: black;
  }
  </style>
<h1 style="text-align:center; color:black;">Task Details</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Priority</th>
    <th>Due Date</th>
    <th>Status</th>
    <th>Created At</th>
  </tr>
  <tr>
    <td> {{task.title}} </td>
    <td> {{task.priority}} </td>
    <td> {{task.due_date}} </td>
    {% if task.is_done == False %}<td>Not completed</td>
    {% else %}<td>Completed</td>{% endif %}
    <td> {{task.created_at}} </td>
  </tr>
</table>
<div style="margin-top: 50px;margin-bottom: 20px;">
<a href="{% url 'task_edit' task.pk %}" class="edit_link1">Edit this task</a>
<a href="{% url 'task_delete' task.pk %}"class="edit_link2">Delete this task?</a>
</div>


         
{% endblock content %}     

tasks/templates/tasks/task_edit.html
{% extends "tasks/base.html" %}
{% block title %}Edit task{% endblock %}
{% block content %}
<style>

.custom-form {
    margin: 20px auto;
    padding: 20px;
    background-color: rgb(180, 193, 203);
    border: 1px solid #ddd;
    border-radius: 5px;
    width: 50%;
    display: grid;
    justify-items: flex-start;
    align-content: center;
  }
  .but3
    {
      height: 55px;
      border: 2px solid black;
      padding: 10px 25px;
      border-radius: 5px;
      color: black;
      font-size: 20px;
      margin-left: 90px;
    }
    .but3:hover
    {
      color: white;
      background-color: black;
      transition: all 1s;
    }
  .submit-button {
    background-color: #4CAF50;
    color: white;
    padding: 15px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  </style>
<h1>Edit task</h1>

<form action="" method="post" class="custom_form">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Update" class="but3">
</form>
{% endblock content %}